### ISSUE TITLE
Add websocket options to web module

### ISSUE THREAD

**Issue by emeroad** [pinpoint-apm/pinpoint#11531]
```yml
pinpoint.web.websocket:
  async-send-timeout:
  max-session-idle-timeout: 10800000 # 3 hours
  max-binary-message-buffer-size:
  max-text-message-buffer-size:
```
