### ISSUE TITLE
Redis connection failure

### ISSUE THREAD

**Issue by DAVE2404** [pinpoint-apm/pinpoint#12246]
``#### Prerequisites
Please check the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and search existing [issues](https://github.com/pinpoint-apm/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ v ] I have checked the [FAQ](https://pinpoint-apm.gitbook.io/pinpoint/faq), and [issues](https://github.com/pinpoint-apm/pinpoint/issues) and found no answer.

I am using Pinpoint 3.0.1 and configured Redis to work on the same host as the Pinpoint Collector, without authentication. Despite confirming that Redis is up and running, I still get a RedisConnectionFailureException when starting the Collector. I am intentionally using Redis, unlike [issue #11880](https://github.com/pinpoint-apm/pinpoint/issues/11880), which discusses avoiding Redis.

application.yml
```
pinpoint:
  zookeeper:
    address: xxx.xxx.xxx.xxx
  metric:
    kafka:
      bootstrap:
        servers: xxx.xxx.xxx.xxx:9092

spring:
  pinot-datasource:
    pinot:
      jdbc-url: jdbc:pinot://xxx.xxx.xxx.xxx:9000
      username: xxx
      password: xxx

  data:
    redis:
      host: localhost
      port: 6379

``` 
I have not configured a Redis password, and verified the following:
Redis is running locally on port 6379.
No password is required (requirepass is not set).

Environment:
Pinpoint/collector version: 3.0.1

Please investigate why Redis authentication is being attempted even when no password is configured. Let me know if there is a workaround or patch needed for this version.

[error.txt](https://github.com/user-attachments/files/19532210/error.txt)
