### ISSUE TITLE
Pinpoint agent in pod container

### ISSUE THREAD

**Issue by Benzion18** [pinpoint-apm/pinpoint#7171]
Hi,
How to add pinpoint agent to kubernetes pod container. How the pod will reach the agent jar? 

I would appreciate an example.

In my case I can't change the container image.

**Comment by emeroad** [comment]
The javaagent option needs to be added to the java command line, so the image needs to be modified.

**Comment by Benzion18** [comment]
Actually I succeeded to do it without modifying the agent image.

1. Add this container to your pod:
```
    - env:
        - name: SPRING_PROFILES
          value: release
        - name: COLLECTOR_IP
          value: <your collector ip>
        - name: PROFILER_TRANSPORT_AGENT_COLLECTOR_PORT
          value: '9991'
        - name: PROFILER_TRANSPORT_METADATA_COLLECTOR_PORT
          value: '9991'
        - name: PROFILER_TRANSPORT_STAT_COLLECTOR_PORT
          value: '9992'
        - name: PROFILER_TRANSPORT_SPAN_COLLECTOR_PORT
          value: '9993'
        - name: PROFILER_SAMPLING_RATE
          value: '1'
        - name: DEBUG_LEVEL
          value: INFO
        - name: PROFILER_TRANSPORT_MODULE
          value: GRPC
      image: 'pinpointdocker/pinpoint-agent:2.0.4'
      imagePullPolicy: Always
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - '-c'
              - sleep 3 ; cp -R /pinpoint-agent /pinpoint-agent2
      name: pinpoint-agent
```

2. Add this to pod volumes:

  ```
volumes:
    - emptyDir: {}
      name: pinpoint-agent-volume
```

3. Add this to your main container volume mounts:

```
      volumeMounts:
        - mountPath: /pinpoint-agent2
          name: pinpoint-agent-volume
```

4. Add this to JVM args:

```
-javaagent:/pinpoint-agent2/pinpoint-agent/pinpoint-bootstrap-2.0.4.jar
            -Dpinpoint.agentId=`echo ${HOSTNAME:${#HOSTNAME}<24?0:-24}`
            -Dpinpoint.applicationName=app1
            -Dpinpoint.profiler.profiles.active=release
```
